"""Конфигурации."""

from pathlib import Path


BASE_DIR = Path(__file__).parent.parent

DATA_DIR = BASE_DIR / "data"
VSDR_IMAGES = DATA_DIR / "VisdroneFrames"
TEST_VIDEO = DATA_DIR / "test_video1.mp4"

PROCESSED_DATA_DIR = DATA_DIR / "processed"
PROCESSED_FRAMES_DIR = PROCESSED_DATA_DIR / "frames"

OUTPUT_DIR = BASE_DIR / "output"
SCREENSHOTS_DIR = OUTPUT_DIR / "screenshots"
OUTPUT_VIDEO_DIR = OUTPUT_DIR / "videos"
METRICS_DIR = OUTPUT_DIR / "metrics"


YOLO_MODEL_NAME = "yolov8x.pt"
CONFIDENCE_THRESHOLD = 0.2
IOU_THRESHOLD = 0.05
DEVICE = "cpu"

TRACKING_ALGORITHM = "CSRT"
MAX_TRACKING_FRAMES = 30
DETECT_EVERY_N_FRAMES = 5

VIDEO_FPS = 30
VIDEO_WIDTH = 640
VIDEO_HEIGHT = 720

MAX_FRAMES_TO_PROCESS = None
FRAME_SKIP = 0

LOG_LEVEL = "INFO"
SAVE_RESULTS = True

IMG_SIZE = 1280
